name: Build custom PCD Excel XLSM

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python -m pip install xlsxwriter git+https://github.com/Beakerboy/MS-OVBA.git
      - run: python build/compile_vba_project.py
      - run: python build/build_xlsm.py
      - uses: actions/upload-artifact@v4
        with:
          name: PCD-Excel-Custom
          path: dist/PCD-Excel-Version-*.xlsm
